version: "3"
services:
  api:
    ports:
      - 80:3333
      - 443:4444
    volumes:
      - /home/ibrahim/.ssl/pickstop/ca_root.crt:/home/os/os_api/ca_root.crt
    depends_on:
      - elasticsearch1
    environment:
      - HTTPS_PORT=${HTTPS_PORT}
    logging:
      options:
        max-size: "25m"
        max-file: "10"
    restart: "unless-stopped"
  elasticsearch1:
    volumes:
      - es-node-1-data:${ES_PATH}/data
      - es-node-1-logs:${ES_PATH}/logs
      - ./elastic/config_1/elasticsearch.yml:${ES_PATH}/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      options:
        max-size: "25m"
        max-file: "10"
    restart: "unless-stopped"
  elasticsearch2:
    volumes:
      - es-node-2-data:${ES_PATH}/data
      - es-node-2-logs:${ES_PATH}/logs
      - es-snapshot:/usr/share/elasticsearch/backup
      - ./elastic/config_2/elasticsearch.yml:${ES_PATH}/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      options:
        max-size: "25m"
        max-file: "10"
    restart: "unless-stopped"
  elasticsearch3:
    volumes:
      - es-node-3-data:${ES_PATH}/data
      - es-node-3-logs:${ES_PATH}/logs
      - ./elastic/config_3/elasticsearch.yml:${ES_PATH}/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      options:
        max-size: "25m"
        max-file: "10"
    restart: "unless-stopped"
  kibana:
    volumes:
      - ./kibana/config/kibana_dev.yml:${KIBANA_PATH}/config/kibana.yml
    logging:
      options:
        max-size: "25m"
        max-file: "10"
    restart: "unless-stopped"
  auth_owner:
    restart: unless-stopped
    logging:
      options:
        max-size: "25m"
        max-file: "10"
  auth_user:
    restart: unless-stopped
    logging:
      options:
        max-size: "25m"
        max-file: "10"
  postgres_owner:
    restart: unless-stopped
    logging:
      options:
        max-size: "25m"
        max-file: "10"
  postgres_user:
    restart: unless-stopped
    logging:
      options:
        max-size: "25m"
        max-file: "10"
  pgadmin:
    restart: unless-stopped
